root: true
ignorePatterns:
  - '!.storybook'
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:promise/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:jest/recommended
  - next/core-web-vitals
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  tsconfigRootDir: .
  project: ./tsconfig.json
  sourceType: module
env:
  node: true
  browser: true
  es2022: true
plugins:
  - import
  - simple-import-sort
  - promise
  - '@typescript-eslint'
  - react
  - jsx-a11y
  - jest
rules:
  react/jsx-boolean-value: error
  react/jsx-curly-brace-presence: error
  react/self-closing-comp:
    - error
    - component: true
      html: true
  '@typescript-eslint/await-thenable': error
  '@typescript-eslint/no-misused-promises':
    - error
    - checksVoidReturn: false
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  simple-import-sort/imports: error
  simple-import-sort/exports: error
settings:
  react:
    pragma: React
    fragment: Fragment
    version: detect
    import/resolver:
      typescript: []
overrides:
  - files:
      - src/*
    rules:
      import/no-default-export: off
      import/prefer-default-export: off
