import './_styles/global.scss';

import { ReactNode } from 'react';

import { Header } from '@/app/_components/Header';
import { notoSansJp } from '@/resources/font';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children?: ReactNode;
};

const RootLayout = ({ children }: Props) => {
  return (
    <html
      lang='ja'
      className={`${notoSansJp.variable}`}
    >
      <head>
        <meta
          name='color-scheme'
          content='light dark'
        />
      </head>

      <body>
        <div className='container'>
          <Header />
          <main
            id='mainContainer'
            tabIndex={0}
          >
            {children}
          </main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
