import { ReactNode } from 'react';

import { notoSansJp } from '../resources/font';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children?: ReactNode;
};

const RootLayout = ({ children }: Props) => {
  return (
    <html
      lang='ja'
      className={`${notoSansJp.variable}`}
    >
      <head>
        <meta
          name='color-scheme'
          content='light dark'
        />
      </head>

      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
